// Generated by CoffeeScript 1.6.3
(function() {
  var db;

  db = require('../db');

  console.log('=== JSON-Based Database Reload Test ===\n\n*  Edit & Save ../db/db.confg at will\n');

  setInterval(function() {
    db.reload();
    console.log(db.admins);
    return console.log(db.projects);
  }, 5000);

}).call(this);
