// Generated by CoffeeScript 1.6.3
(function() {
  var proto, response;

  response = require('express').response;

  proto = response.__proto__;

  proto.error = function(data, session) {
    data.session = session;
    data.disablelogin = true;
    return this.render('error.jade', data);
  };

}).call(this);
