// Generated by CoffeeScript 1.6.3
(function() {
  var errdata, throttlelimit, what;

  errdata = {
    reason: '必须登录才能访问此功能',
    redirect: '/login'
  };

  throttlelimit = 5000;

  what = module.exports;

  what.checkLogin = function(req, res, next) {
    if (!req.session.logined) {
      return res.error(errdata, req.session);
    }
    return next();
  };

  what.throttler = function(req, res, next) {
    var newbie, project;
    project = req.project;
    newbie = project.lastrequest == null;
    if (newbie || (Math.abs(project.lastrequest - Date.now()) > throttlelimit)) {
      project.lastrequest = Date.now();
      return next();
    } else {
      return res.error({
        reason: '项目正忙',
        redirect: "/project/" + project.name
      }, req.session);
    }
  };

}).call(this);
