// Generated by CoffeeScript 1.6.3
(function() {
  var db, forever, refresh, _;

  forever = require('forever');

  _ = require('underscore');

  db = require('./db');

  refresh = function() {
    var projects;
    projects = db.projects;
    return forever.list(null, function(err, data) {
      var procs;
      procs = _.isArray(data) ? data : [];
      procs.forEach(function(proc, i) {
        return proc.index = i;
      });
      projects.forEach(function(project) {
        var _ref;
        return _ref = procs.filter(function(proc) {
          return proc.file === project.file;
        }), project.proc = _ref[0], _ref;
      });
      return null;
    });
  };

  refresh();

  setInterval(refresh, 2000);

  module.exports.refresh = refresh;

}).call(this);
