// Generated by CoffeeScript 1.6.3
(function() {
  var admins, projects, what, _ref;

  _ref = require('./db.json'), admins = _ref.admins, projects = _ref.projects;

  what = module.exports;

  what.reload = function() {
    var _ref1;
    delete require.cache[require.resolve('./db')];
    return _ref1 = require('./db.json'), admins = _ref1.admins, projects = _ref1.projects, _ref1;
  };

  Object.defineProperty(what, 'admins', {
    get: function() {
      return admins;
    }
  });

  Object.defineProperty(what, 'projects', {
    get: function() {
      return projects;
    }
  });

}).call(this);
