// Generated by CoffeeScript 1.6.3
(function() {
  var db, hostinfo;

  db = require('../db');

  hostinfo = require('../misc.js').hostinfo;

  module.exports.apply = function(app) {
    return app.get('/', function(req, res) {
      return res.render('index.jade', {
        projects: db.projects,
        session: req.session,
        hostinfo: hostinfo()
      });
    });
  };

}).call(this);
