// Generated by CoffeeScript 1.6.3
(function() {
  var db, sha1;

  db = require('../db');

  sha1 = require('sha1');

  module.exports.apply = function(app) {
    app.get('/login', function(req, res) {
      return res.render('login.jade', {
        session: req.session,
        disablelogin: true
      });
    });
    return app.post('/login', function(req, res) {
      var admins, password, username, _ref;
      admins = db.admins;
      _ref = req.body, username = _ref.username, password = _ref.password;
      if (password != null) {
        password = sha1(password);
      }
      admins.forEach(function(admin) {
        if (admin.username === username && admin.password === password) {
          req.session.logined = true;
          req.session.username = admin.username;
          return res.redirect('/');
        }
      });
      if (!req.session.logined) {
        return res.error({
          reason: '用户名密码验证错误',
          redirect: '/'
        }, req.session);
      }
    });
  };

}).call(this);
