// Generated by CoffeeScript 1.6.3
(function() {
  module.exports.apply = function(app) {
    return app.get('/logout', function(req, res) {
      req.session = null;
      return res.redirect('/');
    });
  };

}).call(this);
