// Generated by CoffeeScript 1.6.3
(function() {
  var exec, forever, refresh, throttler;

  throttler = require('../middleware.js').throttler;

  refresh = require('../procs.js').refresh;

  exec = require('child_process').exec;

  forever = require('forever');

  module.exports.apply = function(app) {
    return app.get('/project/:project/pull', throttler, function(req, res) {
      var child, cwd, project, session, stderr, stdout;
      project = req.project, session = req.session;
      cwd = (project.file.match(/(.*\/).*$/))[1];
      stdout = '';
      stderr = '';
      child = exec('pwd && git status -v && git pull -v && npm install --color=false ', {
        cwd: cwd
      }, function(err) {
        if (err != null) {
          err = err.message;
        }
        return res.render('project.jade', {
          err: err,
          stdout: stdout,
          stderr: stderr,
          project: project,
          session: session,
          redirect: true
        });
      });
      child.stdout.on('data', function(data) {
        return stdout += data;
      });
      return child.stderr.on('data', function(data) {
        return stderr += data;
      });
    });
  };

}).call(this);
