// Generated by CoffeeScript 1.6.3
(function() {
  var forever, length;

  forever = require('forever');

  length = 50;

  module.exports.apply = function(app) {
    return app.get('/project/:project', function(req, res) {
      var project, session, stdout;
      project = req.project, session = req.session;
      stdout = '';
      if (req.project.proc != null) {
        forever.tail(project.proc.file, {
          length: length,
          stream: false
        }, function(err, log) {
          if (log.line != null) {
            stdout += log.line;
          }
          return stdout += '\n';
        });
      }
      return setTimeout(function() {
        return res.render('project.jade', {
          project: project,
          session: session,
          stdout: stdout
        });
      }, 1000);
    });
  };

}).call(this);
