// Generated by CoffeeScript 1.6.3
(function() {
  var checkLogin, refresh, reload;

  reload = require('../db').reload;

  checkLogin = require('../middleware.js').checkLogin;

  refresh = require('../procs.js').refresh;

  module.exports.apply = function(app) {
    return app.get('/reload', checkLogin, function(res, req) {
      reload();
      refresh();
      return req.redirect('/');
    });
  };

}).call(this);
